package com.example.android.anglaisapp;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.TextView;

public class ReadingActivity extends AppCompatActivity {

    int pressedButtonNumber2;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_reading);

        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        pressedButtonNumber2 = getIntent().getExtras().getInt("buttonNumber2");


        String[] myTexts = {"Today is Saturday.  Usually workers don't go to work on that day so Salif decided to go to Koudougou to visit his relatives.  He left early in the morning at 6 o'clock.  The car he took was not comfortable but for him, what was important was to arrive at his destination\n" + "The car had an accident not far from his village.  The car couldn't go again so they had to change a car and had to wait for hours, but Salif returned home.  It was 4 o'clock in the afternoon.  When he got home, he saw a thief who was trying to break the door of his house.  The thief ran away and forgot his ID card.  Salif took it and knew it that it was Moussa his friend.  What a terrible day!  He thought.",
                "Many animals work for us.  Some are big animals like oxen, donkeys, camels, and elephants.  They carry, pull, and push things.  Some small animals works for us too.  Dogs hunt rabbits and birds, and cats hunt mice.  And we get some of our food from animals.  We eat the meat of cows, pigs and sheep.  We call the meat from cows 'beef', the meat from pig 'pork' and the meat from sheep 'mutton'.  We drink the milk from cows and sheep.  Chickens give us eggs.  And we eat chickens too.  The name of the meat from chicken is chicken.",
                "Air pollution is any visible substance in the air that is not part of the natural composition of the air.  Some air pollution is natural, but pollution created by humans has become a major environmental problem.  Air pollution affects everyone.  It is a threat to the health of human beings and other many other living things on the planet.  Badly polluted air can cause sickenesses and even death. It also damages paint and metal, prevents plants from growing, depletes the ozone layer, an cause a change in climate.  Most of out pollution is caused by thing that people need.  Automobiles and airplanes cause pollution but they also provide people with jobs and products.  In crowded cities, thousands of automobiles and factories can add tons of pollution to the air every day.  Nobody likes air pollution.\n  Everybody wants to stop it but it is a difficult problem to solve.",
                "Internet is a global system of interconnected computer networks connecting billions of users worldwide.  The internet has transformed most traditional communications media including telephone, music, film, and television.  This opened new services, newspapers, and book.\n  Internet made possible new forms of human interactions through SMS, Internet forum and social networking.  Online shopping has developed both for artisans and traders.\n  The origins of the Internet are the 1960s, by the United States government in collaboration with some private commercial interests.  The development of what was by the 1990s an international network resulted in its popularization and incorporation into virtually every aspect of modern human life.\n  In 2013, more than 3 billion people – more than a third of Earth’s population – use the services of the Internet.",
                "In many countries, particularly in developing countries there is a noticeable example of rural to urban migration.  This example is not a new phenomenon. \n" + "There are various reasons for its happening and these reasons may vary from country to country and over periods of time. \n" + "One cause of rural to urban migration may be the lack of jobs in the area.  Many jobs available in rural areas are agricultural based.  The bad weather conditions have decreased the demand for labor in the agricultural sector.  The decrease in the traditional form of employment in rural areas forces many young people to leave the area in search of work in the urban centers of their country. \n" + "Workers may also migrate from rural areas to urban areas in hope of gaining a higher standard of living.  They may leave their current jobs to find higher paying ones as there are many more opportunities for employment to choose in the city. \n" + "Another reason is that people desire to expand their experiences.  They may wish to be exposed to a greater variety of opportunities, people, culture, art, food and entertainment.  The variety that they desire may not be as widely of conveniently available to them in their villages. \n" + "War, famine and natural disaster are also reasons for the rural to urban migration in some countries.  Entire rural populations may migrate to the urban centers of their country in search of protection, food and medical aid during these periods of hardship. ",
                "Tiga was really unlucky.  One day when he was coming back from the nearest village market, he saw his house on fire.  He left his bicycle away and hurried up to put out the fire.  A thief stole the bicycle.  The same night, he heard that his wife who was visiting her parents in her village ran away with another man.  Tiga felt so miserable that he decided to go and see his brother, but he found him sick, lying in hospital.  On his way back home, Tiga was so upset that he didn’t care where he put his feet.  A car knocked him out and he broke his leg.  Tiga felt abandoned by God Himself.  He thought he would rather die.  But what he didn’t know is that at the same time, his first son Kougri who has left three years ago for Cote d’Ivoire was back in his house very sick, unable to speak or move.",
                "My name is Idrissa.  I’m twelve years old.  I live in Wayalghin near Lycee Prive William Ponty. I am a student at this school.  Every morning, before school, I help my father to sell water. So I usually get up early.  This is not a difficult job.  My father is very happy because I help him in his job and I also work well at school.  He promised to buy me a new bicycle.",
                "From Africa to Asia, America as well as Europe, the lives of children are overshadowed by either armed conflict, drought and famine, or by sex and drug abuse.  Children seem to have no place in the lives of adults. \n" + "Nino’s story is typical of the traumatic experiences of most children today.  Nino was a twelve years old Mozambican boy.  He was living in a displaced people’s camp.  Armed bandits had attacked his village in the middle of the night and killed his entire family.  Nino was thought dead. After recovering consciousness, he had found refuge at the camp with other unfortunate children.  But the lowlifes came back and attacked the camp, killing many people.  Nino again was lucky to survive but had no home or family. ",
                "Every four years, athletes go to the Olympic Games.  Each time the games happen in different country – USA in 1984, Korea in 1988 and Spain in 1992.  Many countries compete.  Some countries send a few athletes and others send many.  The flag of Olympic Games has five circles on it, because there are five continents in the world. \n" + "There are many different sports in Olympic Games.  There are indoor sports like boxing and swimming and outdoor sports like rowing and running.  Athletes from African countries in many of the sports, but they are the best at running. \n" + "Athletes win medals at the games.  There is a gold medal for the winner, a silver medal for the second and a bronze medal for the third.  The athlete who wins gold medal is the best in the world. ",
                " It must be said: Incivility is a plague of the new society.  This is worrying! \n" + "Every day, people pose an act of incivility.  In September 2011, a doctor in Bobo-Dioulasso had problems with the son of a patient because he took much time with another.  At Sideradougou, a rural area at 65km from Banfora, a nurse was slapped by a parent of a patient, because she was in the toilet while patients were waiting, as if the caregiver does not feel natural needs. \n" + "Added to that, we notice that people do not respect the road code: traffic lights, stop signs and even roundabouts signals: all this happens on land of upright men.  Citizenship, according to the dictionary, means respect for all the citizens of the community and respect of conventions, the law including respect of the public property. \n" + "Today. There is indiscipline everywhere.  How in high many times have we heard that in high schools, a student insulted and even put his hand on a teacher?  Children no longer respect their parents at home.  That is a situation that challenges everyone.  And pupils actively participate in violent riots and vandalism.  How then can we find the therapy to heal this wound, when we are still concerned about the cost of life?  What to do?  The first act is to restore the authority of the state, but at what cost! \n" + "Anyway, the government must emphasize on the education of the community.  Parents must also involve in the education of their children citizenship and integrity. ",
                "Abiba was the only child of Tassere and Mariama.  She was born when the white men came in Africa.  When she was young, her parents sent her to school so she will be like the white men one day.  She enjoyed school education and she worked hard day and night.  When she got her primary certificate, she was allowed to go to high school.  After her studies, she became a primary school teacher in her own village.  She helped her parents and her neighbors.  They were happy and everybody was encouraged to send boys and girls in Abibata’s school, which became the best school in the area. ",
                "My name is Issa.  I’m fourteen and I am a newspaper boy.  Every morning before school I deliver newspaper, so I have to get up early.  I go to the newspaper shop which is near my home.  I must be there at 7 o’clock.  The shopkeeper gives me the newspaper for about 20 customers a tie.  I put the papers into my bag and I go as fast as I can on my bicycle.  There are lots of different newspapers.  I get 10F on one newspaper that I deliver.  So I earn 7000F CFA a week.  It is not a bad job.  There is a prize every year for the best newspaper boy.  I hope to win the prize this year. ",
                "Every Saturday morning, Mr. and Mrs. Diallo go to the market.  Today, Mr. Diallo is carrying the basket and his wife is walking behind him with their young child on her back.  Men don’t usually go to the market with their wives and the children in the street are looking at him.  The women in the market sometimes greet Mr. Diallo and talk to him.  He often laughs and they can see his beautiful white teeth.  Mr. Diallo wants to buy a nice pair of shoes.  He has small feet and his son can wear his shoes!  He is a good father and he loves his wife and children. \n" + "Mrs. Diallo is also a good wife and a good mother.  Every day, when she comes from the market, she brings a lot of meat, rice and vegetables, and she prepares good food for her family. ",
                "In the human body, there are muscles and bones.  You find long bones in the arms and in the legs.  But the bones in the feet, in the hands, in the fingers and in the toes are very short.  The bones form the skeleton.  Muscles and bones are very important. ",
                "My name is Adama. I’m from Burkina Faso. I go to school in Bobo-Dioulasso. I am in form I. In our classroom, we do six subjects: History, Mathematics, Science, English, Physical education and French.\n" + "We have English on Mondays, on Wednesdays and on Fridays. In Geography, we study the countries of the world, and the history of Africa. I like Geography but I don’t like Mathematics. My best subject is English.",
                "Mrs. Zerbo is Mr. Zerbo’s wife. Mr. Zerbo is Mrs. Zerbo’s husband. Ben and Sali are Mr. Zerbo and Mrs. Zerbo’s children. Ben is Sali’s brother. Sali is Ben’s sister.\n" + "Ben has two children: Seydou and Sita; Sali has one child, his name is Karim. Seydou, Sita and Karim are cousins.\n" + "Ben is Karim’s uncle and Sali is Seydou and Sita’s aunt. Mr. Zerbo and Mrs. Zerbo are Seydou, Sita, and Karim’s grandparents.",
                "Many years ago, the Ministry of Education in Burkina Faso instituted wearing uniforms at schools. This reduced the social difference among students: no difference among students of rich parents and those of poor families. This creates equality for all. Moreover, in their uniforms, they are easily recognizable, so respectable as the future leaders. Unfortunately, some students still refuse to wear it, knowing its importance.\n" + "In one school of Burkina Faso, a pupil dressed in his uniform suddenly fell sick on the way to school. He laid at the road side not able to reach his school. A passer-by saw him and recognized his uniform. He took him to the dispensary and informed the school. Immediately, the student got the right treatment before his parents got the information. What would have happened if he were dressed just like anyone in town?\n" + "What would have happened if the passer-by thought he was just a lazy boy",
                "For me, it is too late now, but I don’t want my children to have the same life that I have had.  My parents did not send me to school. They taught me how to listen and obey. At an early age, they married me to a man that I didn’t choose. Since then, my role has been to serve my husband, to make children, to cook, and to work on the farm. Today, I want my children’s lives to be different.  I’ll send all my children to school to read and to write, so that they will know and enjoy their rights, and have a better life.",
                "Yesterday was a fourteenth birthday, Saturday, 21st May. It was also my cousin Aya’s birthday. So we had one party for both of us at my house. Lots of people came to the party. There were uncles and aunts and cousins as well as friends of our parents. There were many of our friends from the school too.\n" + "When everyone was there, my father and my uncle (Aya’s father) welcomed the guests.  Then Aya and I gave everyone drinks. Then it was time for our birthday cakes. My mother brought them in and put them on the long table. There were candles on the cakes, one for each year. My aunt lit the candles, and everyone sang Happy Birthday. Then Aya and I blew the candles out.\n" + "Everyone talked a lot at first, and then they started dancing. We had a great time. When night came, people started to leave. They said “Thank you for your birthday party and many happy returns.”",
                "In 2009, two teenagers in the Democratic Republic of Congo showed up at their village health clinic, vomiting and with blood in their noses and mouths – hemorrhagic symptoms of the notorious Ebola viruses. In three days, they were dead. Yet, it took three years for researchers to unmask the likely culprit: a brand-new virus called Bas-Congo, which is not related to Ebola or any other virus known to cause hemorrhagic fever.\n" + "It can take weeks or months to identify a novel virus, and much longer if the sample must be sent to a specialized lab, as the Bas-Congo virus was. Deciphering a virus’s genetic code is the critical first step in determining how fast it might spread, identifying possible treatments and even finding vaccines. "};


        String[] Text_names = {"A terrible day", "Farm animals", "Air pollution", "What is Internet", "The causes of rural exodus", "Poor Tiga", "A good student", "What future for the children?", "The Olympic Games", "This is worrying", "A girl's success", "Small jobs", "The Diallo couple", "Muscles and bones", "A student's schedule", "The Zerbo family", "School uniform", "All my children will go to school", "A birthday party", "Bas-Congo virus"};


        String[][] Questions = {
                {"What happened not far from his village", "At what time did Salif return home?", "What did the thief forget when running away?"},
                {"What is the name for the meat of pigs?", "What animals do dogs hunt?", "What animals give us eggs?"},
                {"What is air pollution?", "What are the causes of air pollution?", "What are the harms of polluted air?"},
                {"What is Internet", "What are the influences of Internet?", "How many Internet users are on the planet?"},
                {"What are the causes of this migration?", "In which countries is rural to urban migration most observed?", "What do attract rural populations in towns?"},
                {"What happened when Tiga was coming back from the neighbouring village?", "Why Tiga is an unlucky man?", "Do you think Tiga should really give up and commit suicide?"},
                {"How old is Idrissa?", "What is the profession af Idrissa's father?", "Why does Idrissa have to wake up early?",},
                {"Why was Nino not killed?", "Why did Nino live in a displaced people camp?", "Why does Nino is lucky?"},
                {"How many circles are there on the Olympic Games flag?", "What do the circles on the flag represent?", "What kind of sports are observed at the Olympic Games?",},
                {"What is incivility?", "What are manifestations of incivility in the society?", "What is citizenship?"},
                {"Who is Abiba's father?", "When was Abiba born", "What did Abiba become after her studies?",},
                {"How old is Issa?", "How much does Issa earn a week?", "Why does Issa consider his job as a good one?"},
                {"When do Mr. and Mrs. Diallo go to the market?", "Why is Mr. Diallo a good husband and a good father?", "Why Mrs. Diallo is a good wife and a good mother?"},
                {"What does form the skeleton?", "How are the bones in the arms and in the legs?", "How are the bones in the hands?"},
                {"How many subjects does Adama follow in his class?", "What subject does Adama like?", "When does Adama have English?"},
                {"How many children does Mr. and Mrs. Zerbo have", "Who is Mr. Zerbo's son?", "Who are Karim's cousins?"},
                {"What are the advantages of school uniform?", "Why do you think some students refuse to wear the school uniform", "How did the passer-by know that the boy was a student?",},
                {"Is the narrator in the text a man or a woman?", "Is the narrator a literate or an illiterate?", "What is the role of the narrator in the family?"},
                {"Where does the birthday party happen?", "How old is the narrator?", "Why was the party so great?"},
                {"Enumerate two symptoms of the disease which killed the Congolese teenagers.", "Why did it take three years to identify the Bas-Congo virus?", "How do scientists proceed when they discover a new virus?"},
        };

        TextView TextName = findViewById(R.id.textview_textname);

        TextName.setText(Text_names[pressedButtonNumber2]);

        TextView text = findViewById(R.id.text_view);
        text.setText(myTexts[pressedButtonNumber2]);

        TextView question1 = findViewById(R.id.question_one);
        question1.setText(Questions[pressedButtonNumber2][0]);

        TextView question2 = findViewById(R.id.question_two);
        question2.setText(Questions[pressedButtonNumber2][1]);

        TextView question3 = findViewById(R.id.question_three);
        question3.setText(Questions[pressedButtonNumber2][2]);

    }
}
